version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    build: 
      context: .      
    container_name: rabbitmq-server
    hostname: rabbitserver
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - financialflow-network

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: financialflow
    ports:
      - "5432:5432"
    networks:
      - financialflow-network
      
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - financialflow-network

  financialflow-api:          
    container_name: financialflow_api
    build: 
      context: ../src
      dockerfile: ./Dockerfile.financialFlowSwagger
    ports:
      - "5000:80"
    restart: always 
    environment: 
      ASPNETCORE_ENVIRONMENT: Docker  
      RABBITMQ_HOST: rabbitmq    
      ASPNETCORE_URLS: http://+:80 
      POSTGRES_HOST: postgres
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: financialflow  
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - financialflow-network  

  consume:
    container_name: financialflow_consumer
    build:
      context: ../src
      dockerfile: ./Dockerfile.consumer.financialFlow      
    depends_on:
      - rabbitmq
      - postgres
      - financialflow-api
    environment:
      RABBITMQ_HOST: rabbitmq
      ASPNETCORE_ENVIRONMENT: Docker 
      ASPNETCORE_URLS: http://+:80 
      POSTGRES_HOST: postgres
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: financialflow
    ports:
      - "8080:80" 
    networks:
      - financialflow-network

networks:
  financialflow-network:
    driver: bridge  